Learning Contineous Data prediction

In [1]:
import fastf1
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [2]:
fastf1.Cache.enable_cache('../f1_cache')

In [3]:
session = fastf1.get_session(2021,'Silverstone','R')
session.load()

core           INFO 	Loading data for British Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver  4: Ignoring late data for a previously processed lap.The data may contain errors (previous: 43; current 44)
_api        WARNING 	Driver 55: Ignoring late data for a previously processed lap.The data may contain errors (previous: 7; current 8)
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 44 completed the race distance 00:00.025000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['44', '16', '77', '4', '3', '55', '14', '18', '31', '22', '10', '63', '99', '6', '7', '11', '9', '47', '5', '33']

In [5]:
laps = session.laps
race_laps = laps.pick_quicklaps().copy()


race_laps['LapTime_sec'] = race_laps['LapTime'].dt.total_seconds()


ml_data = race_laps[['Driver', 'LapNumber', 'Compound', 'TyreLife', 'LapTime_sec']].dropna()

display(ml_data.head())

  Driver  LapNumber Compound  TyreLife  LapTime_sec
4    HAM        5.0   MEDIUM       3.0       93.049
5    HAM        6.0   MEDIUM       4.0       93.113
6    HAM        7.0   MEDIUM       5.0       92.738
7    HAM        8.0   MEDIUM       6.0       92.928
8    HAM        9.0   MEDIUM       7.0       93.013

One-hot Encoding

In [8]:
encoded_laps = pd.get_dummies(ml_data,columns=['Compound','Driver'],prefix=['Compound','Driver'])
display(encoded_laps)

,LapNumber,TyreLife,LapTime_sec,Compound_HARD,Compound_MEDIUM,Compound_SOFT,Driver_ALO,Driver_BOT,Driver_GAS,Driver_GIO,...,Driver_NOR,Driver_OCO,Driver_PER,Driver_RAI,Driver_RIC,Driver_RUS,Driver_SAI,Driver_STR,Driver_TSU,Driver_VET
4,5.0,3.0,93.049,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,6.0,4.0,93.113,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,7.0,5.0,92.738,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,8.0,6.0,92.928,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,9.0,7.0,93.013,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,35.0,19.0,93.059,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
964,36.0,20.0,93.545,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
965,37.0,21.0,93.561,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
966,38.0,22.0,93.064,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
967,39.0,23.0,93.721,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
train_data = encoded_laps[encoded_laps['LapNumber'] <= 40]
test_data = encoded_laps[encoded_laps['LapNumber'] > 40]

y_train = train_data['LapTime_sec']
x_train = train_data['']